#!/bin/bash

set -euo pipefail

SUPERPROJECT_ROOT="$(git rev-parse --show-superproject-working-tree)"
if [[ "${SUPERPROJECT_ROOT}" == "" ]]; then
    SUPERPROJECT_ROOT="$(git rev-parse --show-toplevel)"
fi

cd "${SUPERPROJECT_ROOT}/scripts"

format

check

lint
